import { StyleSheet } from "react-native-unistyles";
import "../unistyles";

export const styles = StyleSheet.create((theme) => ({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  header: {
    paddingHorizontal: theme.spacing.xl,
    paddingTop: theme.spacing.md,
    paddingBottom: theme.spacing.xs,
  },
  greeting: {
    fontSize: theme.typography.greeting,
    fontWeight: "700",
    color: theme.colors.textPrimary,
  },
  patientStatus: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    marginTop: 2,
  },
  scrollView: {
    flex: 1,
    paddingHorizontal: theme.spacing.xl,
  },
  sectionTitle: {
    fontSize: theme.typography.sectionTitle,
    fontWeight: "700",
    color: theme.colors.textPrimary,
    marginTop: theme.spacing.lg,
    marginBottom: theme.spacing.md,
  },
  // Alert Card
  alertCard: {
    backgroundColor: theme.colors.red,
    borderRadius: theme.radius.md,
    padding: 18,
    marginBottom: theme.spacing.xl,
  },
  alertRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  alertTitle: {
    fontSize: theme.typography.alertTitle,
    fontWeight: "800",
    color: theme.colors.white,
    letterSpacing: 0.5,
  },
  alertTime: {
    fontSize: 14,
    color: theme.colors.white,
    marginTop: theme.spacing.xs,
    opacity: 0.9,
  },
  callButton: {
    backgroundColor: theme.colors.orange,
    width: 48,
    height: 48,
    borderRadius: theme.radius.full,
    justifyContent: "center",
    alignItems: "center",
  },
  alertActions: {
    flexDirection: "row",
    marginTop: theme.spacing.lg,
    gap: theme.spacing.sm,
  },
  acknowledgeBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.colors.green,
    paddingHorizontal: 14,
    paddingVertical: theme.spacing.sm,
    borderRadius: theme.radius.lg,
    gap: 6,
  },
  emergencyBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.colors.blue,
    paddingHorizontal: 14,
    paddingVertical: theme.spacing.sm,
    borderRadius: theme.radius.lg,
    gap: 6,
  },
  actionBtnText: {
    color: theme.colors.white,
    fontSize: theme.typography.label,
    fontWeight: "600",
  },
  // Metric Cards
  metricsRow: {
    flexDirection: "row",
    marginBottom: theme.spacing.xl,
  },
  heartRateCard: {
    backgroundColor: theme.colors.white,
    borderRadius: theme.radius.md,
    padding: theme.spacing.lg,
    marginRight: theme.spacing.md,
    width: 150,
    borderWidth: 2,
    borderColor: theme.colors.green,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 3,
  },
  spo2Card: {
    backgroundColor: theme.colors.white,
    borderRadius: theme.radius.md,
    padding: theme.spacing.lg,
    marginRight: theme.spacing.md,
    width: 150,
    borderWidth: 2,
    borderColor: theme.colors.blue,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 3,
  },
  locationCard: {
    backgroundColor: theme.colors.white,
    borderRadius: theme.radius.md,
    padding: theme.spacing.lg,
    marginRight: theme.spacing.md,
    width: 150,
    borderWidth: 2,
    borderColor: theme.colors.lightGray,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 3,
  },
  metricLabel: {
    fontSize: theme.typography.label,
    color: theme.colors.textSecondary,
    marginBottom: 6,
  },
  metricValueRow: {
    flexDirection: "row",
    alignItems: "baseline",
  },
  metricValue: {
    fontSize: theme.typography.value,
    fontWeight: "700",
    color: theme.colors.textPrimary,
  },
  metricUnit: {
    fontSize: theme.typography.unit,
    color: theme.colors.textSecondary,
    fontWeight: "500",
  },
  metricValue2: {
    fontSize: theme.typography.value2,
    fontWeight: "700",
    color: theme.colors.textPrimary,
    lineHeight: 26,
  },
  locationIconContainer: {
    marginTop: theme.spacing.sm,
    alignItems: "flex-start",
  },
  chartContainer: {
    marginTop: theme.spacing.sm,
    marginLeft: -4,
    overflow: "hidden",
  },
  // Medicine Card
  medicineCard: {
    backgroundColor: theme.colors.white,
    borderRadius: theme.radius.md,
    padding: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: theme.spacing.xl,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 3,
  },
  medicineContent: {
    flex: 1,
  },
  medicineTitle: {
    fontSize: theme.typography.body,
    fontWeight: "700",
    color: theme.colors.textPrimary,
    marginBottom: theme.spacing.xs,
  },
  medicineName: {
    fontSize: theme.typography.body,
    fontWeight: "600",
    color: theme.colors.textPrimary,
  },
  // Tab Bar
  tabBar: {
    flexDirection: "row",
    backgroundColor: theme.colors.tabBar,
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: theme.spacing.sm,
    justifyContent: "space-around",
  },
  tabItem: {
    alignItems: "center",
    flex: 1,
    gap: theme.spacing.xs,
  },
  tabLabel: {
    fontSize: theme.typography.tab,
    color: theme.colors.white,
    fontWeight: "500",
  },
  tabLabelInactive: {
    fontSize: theme.typography.tab,
    color: theme.colors.textSecondary,
    fontWeight: "500",
  },
}));
