import { StyleSheet } from "react-native-unistyles";
import "../unistyles";

export const styles = StyleSheet.create((theme) => ({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  // Out-of-zone alert banner
  outOfZoneBanner: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 99,
    backgroundColor: theme.colors.red,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: theme.spacing.xl,
    paddingVertical: 12,
    gap: theme.spacing.md,
    shadowColor: theme.colors.red,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  outOfZoneBannerText: {
    flex: 1,
    color: theme.colors.white,
    fontWeight: "700",
    fontSize: theme.typography.body,
  },
  outOfZoneBannerSub: {
    color: theme.colors.white,
    fontSize: theme.typography.label,
    opacity: 0.85,
    marginTop: 2,
  },
  // Map fills all space
  map: {
    flex: 1,
  },
  // Floating header overlay
  headerOverlay: {
    position: "absolute",
    top: 12,
    left: 16,
    right: 16,
    zIndex: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerCard: {
    backgroundColor: theme.colors.white,
    borderRadius: theme.radius.md,
    paddingHorizontal: 14,
    paddingVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 5,
  },
  headerTitle: {
    fontSize: theme.typography.body,
    fontWeight: "700",
    color: theme.colors.textPrimary,
    lineHeight: 20,
  },
  headerSubtitle: {
    fontSize: theme.typography.small,
    color: theme.colors.textSecondary,
    marginTop: 1,
  },
  statusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: theme.colors.white,
    borderRadius: theme.radius.full,
    paddingHorizontal: 12,
    paddingVertical: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 5,
  },
  statusDot: {
    width: 9,
    height: 9,
    borderRadius: theme.radius.full,
  },
  statusPillText: {
    fontSize: theme.typography.label,
    fontWeight: "700",
    color: theme.colors.textPrimary,
  },
  // Bottom panel
  bottomPanel: {
    backgroundColor: theme.colors.white,
    borderTopLeftRadius: theme.radius.lg,
    borderTopRightRadius: theme.radius.lg,
    paddingHorizontal: theme.spacing.xl,
    paddingTop: theme.spacing.lg,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 10,
  },
  panelHandle: {
    width: 36,
    height: 4,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.lightGray,
    alignSelf: "center",
    marginBottom: theme.spacing.lg,
  },
  panelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: theme.spacing.md,
  },
  panelLabel: {
    fontSize: theme.typography.label,
    fontWeight: "700",
    color: theme.colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  panelValue: {
    fontSize: theme.typography.body,
    fontWeight: "700",
    color: theme.colors.textPrimary,
  },
  radiusSliderTrack: {
    height: 6,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.background,
    marginBottom: theme.spacing.lg,
    position: "relative",
    justifyContent: "center",
  },
  radiusSliderFill: {
    height: "100%",
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.blue,
    position: "absolute",
    left: 0,
  },
  radiusSliderThumb: {
    width: 22,
    height: 22,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.blue,
    position: "absolute",
    top: -8,
    shadowColor: theme.colors.blue,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 4,
  },
  infoRow: {
    flexDirection: "row",
    gap: theme.spacing.md,
    marginBottom: theme.spacing.md,
  },
  infoCard: {
    flex: 1,
    backgroundColor: theme.colors.background,
    borderRadius: theme.radius.sm,
    padding: theme.spacing.md,
    alignItems: "center",
    gap: theme.spacing.xs,
  },
  infoCardValue: {
    fontSize: theme.typography.body,
    fontWeight: "700",
    color: theme.colors.textPrimary,
  },
  infoCardLabel: {
    fontSize: theme.typography.small,
    color: theme.colors.textSecondary,
    fontWeight: "500",
  },
  setZoneButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing.sm,
    backgroundColor: theme.colors.tabBar,
    borderRadius: theme.radius.md,
    paddingVertical: theme.spacing.md,
    marginBottom: theme.spacing.md,
  },
  setZoneButtonText: {
    fontSize: theme.typography.body,
    fontWeight: "700",
    color: theme.colors.white,
  },
  // Tab Bar
  tabBar: {
    flexDirection: "row",
    backgroundColor: theme.colors.tabBar,
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: theme.spacing.sm,
    justifyContent: "space-around",
  },
  tabItem: {
    alignItems: "center",
    flex: 1,
    gap: theme.spacing.xs,
  },
  tabLabel: {
    fontSize: 11,
    color: theme.colors.white,
    fontWeight: "500",
  },
  tabLabelInactive: {
    fontSize: 11,
    color: theme.colors.textSecondary,
    fontWeight: "500",
  },
  // Permission screen
  permissionContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 32,
    gap: 16,
  },
  permissionIcon: {
    width: 80,
    height: 80,
    borderRadius: 9999,
    backgroundColor: "#E3F2FD",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
  },
  permissionTitle: {
    fontSize: theme.typography.sectionTitle,
    fontWeight: "700",
    color: theme.colors.textPrimary,
    textAlign: "center",
  },
  permissionSub: {
    fontSize: theme.typography.body,
    color: theme.colors.textSecondary,
    textAlign: "center",
    lineHeight: 22,
  },
  permissionButton: {
    backgroundColor: theme.colors.tabBar,
    borderRadius: theme.radius.md,
    paddingHorizontal: 32,
    paddingVertical: theme.spacing.lg,
    marginTop: 8,
  },
  permissionButtonText: {
    color: theme.colors.white,
    fontWeight: "700",
    fontSize: theme.typography.body,
  },
}));
