import { StyleSheet } from "react-native-unistyles";
import "../unistyles";

export const styles = StyleSheet.create((theme) => ({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  header: {
    paddingHorizontal: theme.spacing.xl,
    paddingTop: theme.spacing.md,
    paddingBottom: theme.spacing.xs,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: theme.typography.greeting,
    fontWeight: "700",
    color: theme.colors.textPrimary,
  },
  addButton: {
    width: 40,
    height: 40,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.tabBar,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
  },
  scrollView: {
    flex: 1,
    paddingHorizontal: theme.spacing.xl,
    paddingTop: theme.spacing.lg,
  },
  // Summary Banner
  summaryBanner: {
    backgroundColor: theme.colors.tabBar,
    borderRadius: theme.radius.md,
    padding: theme.spacing.lg,
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: theme.spacing.xl,
  },
  summaryItem: {
    alignItems: "center",
    gap: theme.spacing.xs,
  },
  summaryValue: {
    fontSize: 22,
    fontWeight: "700",
    color: theme.colors.white,
  },
  summaryLabel: {
    fontSize: theme.typography.small,
    color: "#9E9EC8",
    fontWeight: "500",
  },
  summaryDivider: {
    width: 1,
    backgroundColor: "#FFFFFF22",
    alignSelf: "stretch",
  },
  // Alarm Card
  alarmCard: {
    backgroundColor: theme.colors.white,
    borderRadius: theme.radius.md,
    marginBottom: theme.spacing.lg,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
    overflow: "hidden",
  },
  alarmCardDisabled: {
    opacity: 0.55,
  },
  alarmCardAccent: {
    height: 4,
  },
  alarmCardBody: {
    padding: theme.spacing.lg,
  },
  alarmTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: theme.spacing.sm,
  },
  alarmTimeBlock: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 6,
  },
  alarmTime: {
    fontSize: 48,
    fontWeight: "200",
    color: theme.colors.textPrimary,
    letterSpacing: -1,
    lineHeight: 52,
  },
  alarmTimeDisabled: {
    color: theme.colors.textSecondary,
  },
  alarmAmPm: {
    fontSize: 18,
    fontWeight: "400",
    color: theme.colors.textSecondary,
    marginBottom: 4,
  },
  alarmMeta: {
    marginBottom: theme.spacing.md,
  },
  alarmName: {
    fontSize: theme.typography.body,
    fontWeight: "700",
    color: theme.colors.textPrimary,
    marginBottom: 2,
  },
  alarmDose: {
    fontSize: theme.typography.label,
    color: theme.colors.textSecondary,
  },
  alarmDivider: {
    height: 1,
    backgroundColor: theme.colors.background,
    marginBottom: theme.spacing.md,
  },
  alarmBottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  daysRow: {
    flexDirection: "row",
    gap: 5,
  },
  dayChip: {
    width: 28,
    height: 28,
    borderRadius: theme.radius.full,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: theme.colors.background,
  },
  dayChipActive: {
    width: 28,
    height: 28,
    borderRadius: theme.radius.full,
    justifyContent: "center",
    alignItems: "center",
  },
  dayChipText: {
    fontSize: 11,
    fontWeight: "600",
    color: theme.colors.textSecondary,
  },
  dayChipTextActive: {
    fontSize: 11,
    fontWeight: "700",
    color: theme.colors.white,
  },
  durationBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: theme.colors.background,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: theme.radius.sm,
  },
  durationText: {
    fontSize: theme.typography.small,
    color: theme.colors.textSecondary,
    fontWeight: "500",
  },
  durationTextPermanent: {
    fontSize: theme.typography.small,
    color: theme.colors.green,
    fontWeight: "600",
  },
  // Empty State
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
    gap: theme.spacing.md,
  },
  emptyIcon: {
    width: 72,
    height: 72,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.white,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: theme.spacing.sm,
  },
  emptyTitle: {
    fontSize: theme.typography.body,
    fontWeight: "700",
    color: theme.colors.textPrimary,
  },
  emptySubtitle: {
    fontSize: theme.typography.label,
    color: theme.colors.textSecondary,
    textAlign: "center",
    lineHeight: 20,
  },
  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: "#00000066",
    justifyContent: "flex-end",
  },
  modalSheet: {
    backgroundColor: theme.colors.white,
    borderTopLeftRadius: theme.radius.lg,
    borderTopRightRadius: theme.radius.lg,
    paddingHorizontal: theme.spacing.xl,
    paddingBottom: 36,
    paddingTop: theme.spacing.xl,
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.lightGray,
    alignSelf: "center",
    marginBottom: theme.spacing.xl,
  },
  modalTitle: {
    fontSize: theme.typography.sectionTitle,
    fontWeight: "700",
    color: theme.colors.textPrimary,
    marginBottom: theme.spacing.xl,
  },
  fieldLabel: {
    fontSize: theme.typography.label,
    fontWeight: "700",
    color: theme.colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: theme.spacing.sm,
    marginTop: theme.spacing.lg,
  },
  textInput: {
    backgroundColor: theme.colors.background,
    borderRadius: theme.radius.sm,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.md,
    fontSize: theme.typography.body,
    color: theme.colors.textPrimary,
    fontWeight: "500",
  },
  timePickerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.md,
  },
  timePickerBox: {
    flex: 1,
    backgroundColor: theme.colors.background,
    borderRadius: theme.radius.sm,
    paddingVertical: theme.spacing.md,
    alignItems: "center",
  },
  timePickerText: {
    fontSize: 32,
    fontWeight: "200",
    color: theme.colors.textPrimary,
    letterSpacing: -0.5,
  },
  timePickerSep: {
    fontSize: 28,
    fontWeight: "200",
    color: theme.colors.textSecondary,
  },
  amPmRow: {
    flexDirection: "row",
    gap: theme.spacing.sm,
    marginTop: theme.spacing.sm,
  },
  amPmChip: {
    flex: 1,
    paddingVertical: theme.spacing.sm,
    borderRadius: theme.radius.sm,
    backgroundColor: theme.colors.background,
    alignItems: "center",
  },
  amPmChipActive: {
    flex: 1,
    paddingVertical: theme.spacing.sm,
    borderRadius: theme.radius.sm,
    alignItems: "center",
  },
  amPmText: {
    fontSize: theme.typography.label,
    fontWeight: "600",
    color: theme.colors.textSecondary,
  },
  amPmTextActive: {
    fontSize: theme.typography.label,
    fontWeight: "700",
    color: theme.colors.white,
  },
  modalDaysRow: {
    flexDirection: "row",
    gap: theme.spacing.sm,
  },
  modalDayChip: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: theme.radius.sm,
    backgroundColor: theme.colors.background,
    alignItems: "center",
  },
  modalDayChipActive: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: theme.radius.sm,
    alignItems: "center",
  },
  modalDayText: {
    fontSize: theme.typography.small,
    fontWeight: "600",
    color: theme.colors.textSecondary,
  },
  modalDayTextActive: {
    fontSize: theme.typography.small,
    fontWeight: "700",
    color: theme.colors.white,
  },
  durationToggleRow: {
    flexDirection: "row",
    gap: theme.spacing.sm,
  },
  durationToggleChip: {
    flex: 1,
    paddingVertical: theme.spacing.md,
    borderRadius: theme.radius.sm,
    backgroundColor: theme.colors.background,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
  },
  durationToggleChipActive: {
    flex: 1,
    paddingVertical: theme.spacing.md,
    borderRadius: theme.radius.sm,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
  },
  durationToggleText: {
    fontSize: theme.typography.label,
    fontWeight: "600",
    color: theme.colors.textSecondary,
  },
  durationToggleTextActive: {
    fontSize: theme.typography.label,
    fontWeight: "700",
    color: theme.colors.white,
  },
  dateRangeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.sm,
    marginTop: theme.spacing.sm,
  },
  dateBox: {
    flex: 1,
    backgroundColor: theme.colors.background,
    borderRadius: theme.radius.sm,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.md,
    alignItems: "center",
  },
  dateBoxLabel: {
    fontSize: theme.typography.small,
    color: theme.colors.textSecondary,
    fontWeight: "500",
    marginBottom: 2,
  },
  dateBoxValue: {
    fontSize: theme.typography.label,
    fontWeight: "700",
    color: theme.colors.textPrimary,
  },
  dateRangeArrow: {
    color: theme.colors.textSecondary,
    fontSize: 18,
  },
  saveButton: {
    borderRadius: theme.radius.md,
    paddingVertical: theme.spacing.lg,
    alignItems: "center",
    marginTop: theme.spacing.xl,
  },
  saveButtonText: {
    fontSize: theme.typography.body,
    fontWeight: "700",
    color: theme.colors.white,
    letterSpacing: 0.3,
  },
  // Tab Bar
  tabBar: {
    flexDirection: "row",
    backgroundColor: theme.colors.tabBar,
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: theme.spacing.sm,
    justifyContent: "space-around",
  },
  tabItem: {
    alignItems: "center",
    flex: 1,
    gap: theme.spacing.xs,
  },
  tabLabel: {
    fontSize: 11,
    color: theme.colors.white,
    fontWeight: "500",
  },
  tabLabelInactive: {
    fontSize: 11,
    color: theme.colors.textSecondary,
    fontWeight: "500",
  },
}));
